export const projectContainer: string;
export const projectImageContainer: string;
export const title: string;
export const projectDescription: string;
export const projectStills: string;
export const projectStillsImageContainer: string;
export const relatedProjectsContainer: string;
export const playerWrapper: string;
export const reactPlayer: string;
